import { Router } from "express";// Importación de la función Router del módulo "express" para crear un enrutador de Express, lo que permite a este módulo definir rutas específicas para manejar las solicitudes relacionadas con la autenticación en la aplicación, mejorando la organización del código al separar las rutas relacionadas con la autenticación en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con la autenticación en este enrutador
import { AuthController } from "./auth.controller";// Importación del controlador de autenticación para manejar las solicitudes relacionadas con la autenticación, lo que permite a este módulo delegar la lógica de negocio relacionada con la autenticación a este controlador, mejorando la organización del código al separar las responsabilidades entre el enrutador y el controlador, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con la autenticación en este controlador
import { authMiddleware } from "../../middlewares/authMiddleware";// Importación del middleware de autenticación para proteger las rutas relacionadas con la autenticación, lo que permite a este módulo asegurar que solo los usuarios autenticados puedan acceder a ciertas rutas relacionadas con la autenticación, mejorando la seguridad de la aplicación al controlar el acceso a estas rutas según el estado de autenticación del usuario
import { roleMiddleware } from "../../middlewares/roleMiddleware";// Importación del middleware de roles para proteger las rutas relacionadas con la autenticación, lo que permite a este módulo asegurar que solo los usuarios con los roles adecuados puedan acceder a ciertas rutas relacionadas con la autenticación, mejorando la seguridad de la aplicación al controlar el acceso a estas rutas según los roles de los usuarios autenticados

export const router = Router();// Creación de un nuevo enrutador de Express para manejar las rutas relacionadas con la autenticación, lo que permite a este módulo definir rutas específicas para manejar las solicitudes relacionadas con la autenticación en la aplicación, mejorando la organización del código al separar las rutas relacionadas con la autenticación en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con la autenticación en este enrutador

router.post("/register", AuthController.register);// Ruta para manejar el registro de un nuevo usuario, lo que permite a este módulo definir una ruta específica para manejar las solicitudes POST relacionadas con el registro de usuarios en la aplicación, mejorando la organización del código al separar las rutas relacionadas con la autenticación en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con la autenticación en este enrutador
router.post("/login", AuthController.login);// Ruta para manejar el inicio de sesión de un usuario, lo que permite a este módulo definir una ruta específica para manejar las solicitudes POST relacionadas con el inicio de sesión de usuarios en la aplicación, mejorando la organización del código al separar las rutas relacionadas con la autenticación en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con la autenticación en este enrutador
router.post("/refresh", AuthController.refresh);// Ruta para manejar la actualización del token de autenticación de un usuario, lo que permite a este módulo definir una ruta específica para manejar las solicitudes POST relacionadas con la actualización del token de autenticación en la aplicación, mejorando la organización del código al separar las rutas relacionadas con la autenticación en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con la autenticación en este enrutador
router.get("/me", authMiddleware, AuthController.me);// Ruta para manejar la obtención de la información del usuario autenticado, protegida por el middleware de autenticación para asegurar que solo los usuarios autenticados puedan acceder a esta ruta y realizar la operación de obtención de la información del usuario autenticado, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación del usuario

router.post(// Ruta para manejar una operación de ejemplo que solo los usuarios con el rol de "gestor" pueden acceder, protegida por el middleware de autenticación y el middleware de roles para asegurar que solo los usuarios autenticados con el rol de "gestor" puedan acceder a esta ruta y realizar la operación definida en el controlador, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación y los roles de los usuarios
  "/admin-only",// Ruta para manejar una operación de ejemplo que solo los usuarios con el rol de "gestor" pueden acceder, lo que permite a este módulo definir una ruta específica para manejar las solicitudes POST relacionadas con esta operación de ejemplo en la aplicación, mejorando la organización del código al separar las rutas relacionadas con la autenticación en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con la autenticación en este enrutador
  authMiddleware,// Middleware de autenticación para proteger esta ruta, lo que permite a este módulo asegurar que solo los usuarios autenticados puedan acceder a esta ruta y realizar la operación definida en el controlador, mejorando la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación del usuario
  roleMiddleware(["gestor"]),// Middleware de roles para proteger esta ruta, lo que permite a este módulo asegurar que solo los usuarios con el rol de "gestor" puedan acceder a esta ruta y realizar la operación definida en el controlador, mejorando la seguridad de la aplicación al controlar el acceso a esta ruta según los roles de los usuarios autenticados
  (req, res) => { res.json({ message: "Solo gestores" }); }// Controlador de ejemplo para manejar la operación de esta ruta, lo que permite a este módulo definir una función de controlador específica para manejar las solicitudes POST relacionadas con esta operación de ejemplo en la aplicación, mejorando la organización del código al separar las responsabilidades entre el enrutador y el controlador, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con esta operación de ejemplo en este controlador
);// Ruta para manejar una operación de ejemplo que solo los usuarios con el rol de "gestor" pueden acceder, lo que permite a este módulo definir una ruta específica para manejar las solicitudes POST relacionadas con esta operación de ejemplo en la aplicación, mejorando la organización del código al separar las rutas relacionadas con la autenticación en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con la autenticación en este enrutador

export default router;
