import { Request, Response } from "express"; // Importación de los tipos Request y Response del módulo "express" para definir los tipos de los parámetros de las funciones en esta clase, lo que permite a este módulo manejar las solicitudes HTTP entrantes y enviar respuestas HTTP adecuadas al cliente, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar una estructura clara para el manejo de las operaciones relacionadas con la autenticación y el perfil de usuario
import Boom from "@hapi/boom";//  Importación de la biblioteca Boom para manejar errores de manera más estructurada y consistente en esta clase, lo que permite a este módulo lanzar errores con códigos de estado HTTP específicos y mensajes claros, mejorando la gestión de errores en la aplicación al proporcionar información útil sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con la autenticación y el perfil de usuario
import {
  getProfileService,// Importación del servicio para obtener el perfil de un usuario, lo que permite a este módulo delegar la lógica de negocio relacionada con la obtención del perfil de usuario a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con el perfil de usuario en este servicio
  loginUserService,// Importación del servicio para manejar el login de un usuario, lo que permite a este módulo delegar la lógica de negocio relacionada con el login de usuario a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con el login de usuario en este servicio
  registerUserService,// Importación del servicio para manejar el registro de un nuevo usuario, lo que permite a este módulo delegar la lógica de negocio relacionada con el registro de usuario a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con el registro de usuario en este servicio
  refreshTokenService,// Importación del servicio para manejar la renovación de tokens de autenticación, lo que permite a este módulo delegar la lógica de negocio relacionada con la renovación de tokens a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con la renovación de tokens en este servicio
  type RegisterResult,//  Importación del tipo RegisterResult para definir el tipo de resultado que se espera obtener al registrar un nuevo usuario, lo que permite a este módulo manejar de manera clara y estructurada los diferentes resultados que pueden ocurrir durante el proceso de registro de usuario, mejorando la gestión de resultados en la aplicación al proporcionar una estructura clara para los resultados relacionados con el registro de usuario
} from "./auth.service";// Importación de los servicios relacionados con la autenticación para manejar las operaciones de registro, login, obtención de perfil y renovación de tokens, lo que permite a este módulo delegar la lógica de negocio relacionada con estas operaciones a estos servicios, mejorando la organización del código al separar las responsabilidades entre el controlador y los servicios, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con la autenticación en estos servicios
import { LoginDTO, RegisterDTO } from "./auth.types";// Importación de los tipos LoginDTO y RegisterDTO para definir el tipo de datos que se espera recibir en las solicitudes de login y registro de usuario, lo que permite a este módulo manejar de manera clara y estructurada los datos relacionados con estas operaciones, mejorando la gestión de datos en la aplicación al proporcionar una estructura clara para los datos relacionados con el login y el registro de usuario
import { AuthRequest } from "../../middlewares/authMiddleware";// Importación del tipo AuthRequest para definir el tipo de solicitud que se espera recibir en las operaciones que requieren autenticación, lo que permite a este módulo manejar de manera clara y estructurada las solicitudes relacionadas con la autenticación, mejorando la gestión de solicitudes en la aplicación al proporcionar una estructura clara para las solicitudes que requieren autenticación y facilitar el acceso a la información del usuario autenticado en estas operaciones

const getErrorMessage = (error: unknown, defaultMessage: string) => { // Función para obtener el mensaje de error a partir de un error desconocido, lo que permite a esta función manejar de manera clara y estructurada los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con la autenticación, mejorando la gestión de errores en la aplicación al proporcionar información útil sobre los errores que puedan ocurrir durante la ejecución de estas operaciones
  if (error instanceof Error) return error.message;// Si el error es una instancia de Error, devuelve su mensaje, lo que permite a esta función proporcionar información clara sobre el error que ocurrió durante la ejecución de una operación relacionada con la autenticación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de estas operaciones
  return defaultMessage;// Si el error no es una instancia de Error, devuelve un mensaje predeterminado, lo que permite a esta función proporcionar información clara sobre el error que ocurrió durante la ejecución de una operación relacionada con la autenticación, incluso en casos donde el error no sea una instancia de Error, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de estas operaciones
};

const getStatusCode = (error: unknown, defaultStatus: number) => {// Función para obtener el código de estado HTTP a partir de un error desconocido, lo que permite a esta función manejar de manera clara y estructurada los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con la autenticación, mejorando la gestión de errores en la aplicación al proporcionar información útil sobre los errores que puedan ocurrir durante la ejecución de estas operaciones y permitir responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió
  if (Boom.isBoom(error)) return error.output.statusCode;// Si el error es un error de Boom, devuelve su código de estado HTTP, lo que permite a esta función proporcionar información clara sobre el error que ocurrió durante la ejecución de una operación relacionada con la autenticación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de estas operaciones, y responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió
  return defaultStatus;// Si el error no es un error de Boom, devuelve un código de estado HTTP predeterminado, lo que permite a esta función proporcionar información clara sobre el error que ocurrió durante la ejecución de una operación relacionada con la autenticación, incluso en casos donde el error no sea un error de Boom, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de estas operaciones, y responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió
};

export class AuthController {// Clase para manejar las operaciones relacionadas con la autenticación, lo que permite a esta clase definir métodos estáticos para manejar las solicitudes HTTP relacionadas con el registro, login, obtención de perfil y renovación de tokens, mejorando la organización del código al centralizar las operaciones relacionadas con la autenticación en esta clase, y facilitando el mantenimiento y la escalabilidad de la aplicación al proporcionar una estructura clara para el manejo de estas operaciones
  static async register(req: Request<unknown, unknown, RegisterDTO>, res: Response) {// Método estático para manejar el registro de un nuevo usuario, lo que permite a este método ser llamado sin necesidad de instanciar la clase AuthController, facilitando su uso en las rutas de Express para manejar las solicitudes POST relacionadas con el registro de usuario en la aplicación
    try {// Manejo de la lógica para registrar un nuevo usuario, lo que permite a este método procesar la solicitud de registro de usuario, delegar la lógica de negocio relacionada con el registro al servicio registerUserService, y responder al cliente con la información del resultado del registro o un mensaje de error en caso de que ocurra un error durante el proceso, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado del registro de usuario
      const result: RegisterResult = await registerUserService(req.body);// Llamada al servicio registerUserService para manejar la lógica de negocio relacionada con el registro de un nuevo usuario, lo que permite a este método delegar la lógica de negocio relacionada con el registro de usuario a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con el registro de usuario en este servicio
      if (result.type === "email_confirmation") {// Si el resultado del registro indica que se requiere confirmación de correo electrónico, responde al cliente con un mensaje indicando que se ha enviado un correo de confirmación, lo que permite a este método manejar de manera clara y estructurada los diferentes resultados que pueden ocurrir durante el proceso de registro de usuario, mejorando la gestión de resultados en la aplicación al proporcionar información clara sobre el resultado del registro de usuario y las acciones que el cliente debe tomar a continuación
        return res.status(202).json({ message: result.message });// Respuesta con el código de estado 202 (Accepted) y un mensaje indicando que se ha enviado un correo de confirmación, lo que indica al cliente que la solicitud de registro de usuario ha sido aceptada y que se requiere una acción adicional (confirmación de correo electrónico) para completar el proceso de registro, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado del registro de usuario y las acciones que el cliente debe tomar a continuación
      }
      res.status(201).json(result.data);// Respuesta con el código de estado 201 (Created) y la información del usuario registrado en formato JSON, lo que indica al cliente que la solicitud de registro de usuario ha sido procesada exitosamente y que se ha creado un nuevo usuario, proporcionando la información del usuario registrado en la respuesta para que el cliente pueda utilizarla según sea necesario, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado del registro de usuario
    } catch (error: unknown) {// Manejo de errores en caso de que ocurra un error durante el proceso de registro de usuario, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación
      res.status(getStatusCode(error, 400)).json({ error: getErrorMessage(error, "Registro fallido") });// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 400 (Bad Request) y un mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de esta operación
    }
  }

  static async login(req: Request<unknown, unknown, LoginDTO>, res: Response) {// Método estático para manejar el login de un usuario, lo que permite a este método ser llamado sin necesidad de instanciar la clase AuthController, facilitando su uso en las rutas de Express para manejar las solicitudes POST relacionadas con el login de usuario en la aplicación
    try {// Manejo de la lógica para realizar el login de un usuario, lo que permite a este método procesar la solicitud de login de usuario, delegar la lógica de negocio relacionada con el login al servicio loginUserService, y responder al cliente con la información del resultado del login o un mensaje de error en caso de que ocurra un error durante el proceso, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado del login de usuario
      const result = await loginUserService(req.body);// Llamada al servicio loginUserService para manejar la lógica de negocio relacionada con el login de un usuario, lo que permite a este método delegar la lógica de negocio relacionada con el login de usuario a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con el login de usuario en este servicio
      res.status(200).json(result);// Respuesta con el código de estado 200 (OK) y la información del resultado del login en formato JSON, lo que indica al cliente que la solicitud de login de usuario ha sido procesada exitosamente y proporciona la información del resultado del login en la respuesta para que el cliente pueda utilizarla según sea necesario, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado del login de usuario
    } catch (error: unknown) {// Manejo de errores en caso de que ocurra un error durante el proceso de login de usuario, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación
      res.status(getStatusCode(error, 401)).json({ error: getErrorMessage(error, "Login fallido") });// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 401 (Unauthorized) y un mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de esta operación
    }
  }

  static async refresh(req: Request<unknown, unknown, { refreshToken: string }>, res: Response) {// Método estático para manejar la renovación de tokens de autenticación, lo que permite a este método ser llamado sin necesidad de instanciar la clase AuthController, facilitando su uso en las rutas de Express para manejar las solicitudes POST relacionadas con la renovación de tokens en la aplicación
    try {
      const { refreshToken } = req.body;// Extracción del token de renovación de la solicitud, lo que permite a este método obtener el token de renovación enviado por el cliente en la solicitud HTTP para utilizarlo en el proceso de renovación de tokens, mejorando la gestión de datos en la aplicación al proporcionar una estructura clara para los datos necesarios en esta operación
      if (!refreshToken) {// Verificación de que se ha proporcionado un token de renovación en la solicitud, lo que permite a este método manejar de manera clara y estructurada el caso en que el cliente no proporciona un token de renovación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación y responder al cliente con un mensaje de error adecuado
        return res.status(400).json({ error: "refreshToken requerido" });// Respuesta con el código de estado 400 (Bad Request) y un mensaje de error indicando que se requiere un token de renovación, lo que indica al cliente que la solicitud de renovación de tokens no se ha procesado debido a la falta de un token de renovación en la solicitud, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación y responder al cliente con un mensaje de error adecuado
      }
      const result = await refreshTokenService(refreshToken);// Llamada al servicio refreshTokenService para manejar la lógica de negocio relacionada con la renovación de tokens de autenticación, lo que permite a este método delegar la lógica de negocio relacionada con la renovación de tokens a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con la renovación de tokens en este servicio
      res.status(200).json(result);// Respuesta con el código de estado 200 (OK) y la información del resultado de la renovación de tokens en formato JSON, lo que indica al cliente que la solicitud de renovación de tokens ha sido procesada exitosamente y proporciona la información del resultado de la renovación de tokens en la respuesta para que el cliente pueda utilizarla según sea necesario, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado de la renovación de tokens
    } catch (error: unknown) {// Manejo de errores en caso de que ocurra un error durante el proceso de renovación de tokens, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación y responder al cliente con un mensaje de error adecuado
      res.status(getStatusCode(error, 401)).json({ error: getErrorMessage(error, "No se pudo renovar la sesión") });// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 401 (Unauthorized) y un mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de esta operación y responder al cliente con un mensaje de error adecuado
    }
  }

  static async me(req: AuthRequest, res: Response) {// Método estático para manejar la obtención del perfil del usuario autenticado, lo que permite a este método ser llamado sin necesidad de instanciar la clase AuthController, facilitando su uso en las rutas de Express para manejar las solicitudes GET relacionadas con la obtención del perfil de usuario en la aplicación
    try {// Manejo de la lógica para obtener el perfil del usuario autenticado, lo que permite a este método procesar la solicitud de obtención del perfil de usuario, delegar la lógica de negocio relacionada con la obtención del perfil al servicio getProfileService, y responder al cliente con la información del perfil de usuario o un mensaje de error en caso de que ocurra un error durante el proceso, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado de la obtención del perfil de usuario
      const user = req.user;// Obtención de la información del usuario autenticado a partir de la solicitud, lo que permite a este método acceder a la información del usuario autenticado para utilizarla en el proceso de obtención del perfil de usuario, mejorando la gestión de datos en la aplicación al proporcionar una estructura clara para acceder a la información del usuario autenticado en las operaciones que requieren autenticación
      if (!user?.id) throw new Error("Usuario no autenticado");// Verificación de que se ha obtenido la información del usuario autenticado y que se ha obtenido su ID, lo que permite a este método manejar de manera clara y estructurada el caso en que no se ha obtenido la información del usuario autenticado o no se ha obtenido su ID, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación y responder al cliente con un mensaje de error adecuado
      const profile = await getProfileService(user.id);// Llamada al servicio getProfileService para manejar la lógica de negocio relacionada con la obtención del perfil de un usuario, lo que permite a este método delegar la lógica de negocio relacionada con la obtención del perfil de usuario a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con el perfil de usuario en este servicio
      res.status(200).json(profile);// Respuesta con el código de estado 200 (OK) y la información del perfil de usuario en formato JSON, lo que indica al cliente que la solicitud de obtención del perfil de usuario ha sido procesada exitosamente y proporciona la información del perfil de usuario en la respuesta para que el cliente pueda utilizarla según sea necesario, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado de la obtención del perfil de usuario
    } catch (error: unknown) {// Manejo de errores en caso de que ocurra un error durante el proceso de obtención del perfil de usuario, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación y responder al cliente con un mensaje de error adecuado
      res.status(getStatusCode(error, 401)).json({ error: getErrorMessage(error, "No se pudo obtener el perfil") });// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 401 (Unauthorized) y un mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de esta operación y responder al cliente con un mensaje de error adecuado
    }
  }
}
