import { Response } from "express";// Importación del tipo Response del módulo "express" para tipar los objetos de respuesta en los métodos del controlador, lo que permite a este controlador manejar las respuestas HTTP de manera adecuada al proporcionar la información necesaria para enviar respuestas al cliente con el formato y el contenido correcto según las operaciones realizadas en las rutas relacionadas con las asistencias en la aplicación
import Boom from "@hapi/boom";// Importación del módulo Boom para manejar errores de manera estructurada y consistente en el controlador, lo que permite a este controlador lanzar errores con mensajes claros y códigos de estado HTTP adecuados según el tipo de error que ocurra durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, mejorando la gestión de errores al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de estas operaciones
import { AuthRequest } from "../../middlewares/authMiddleware";// Importación del tipo AuthRequest del middleware de autenticación para tipar los objetos de solicitud en los métodos del controlador, lo que permite a este controlador manejar las solicitudes HTTP de manera adecuada al proporcionar la información necesaria para acceder a los datos de autenticación del usuario en las rutas relacionadas con las asistencias en la aplicación, mejorando la gestión de solicitudes al permitir a los desarrolladores trabajar con la información de autenticación de manera eficiente y clara durante la ejecución de estas operaciones
import {
  getBalanceService,// Importación del servicio getBalanceService para manejar la lógica de negocio relacionada con la obtención del balance de asistencias de un usuario, lo que permite a este controlador delegar esta lógica de negocio a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
  getHistorialService,// Importación del servicio getHistorialService para manejar la lógica de negocio relacionada con la obtención del historial de asistencias de un usuario, lo que permite a este controlador delegar esta lógica de negocio a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
  scanQRService,// Importación del servicio scanQRService para manejar la lógica de negocio relacionada con el escaneo de códigos QR para registrar asistencias, lo que permite a este controlador delegar esta lógica de negocio a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
} from "./asistencias.service";// Importación de los servicios relacionados con las asistencias para manejar la lógica de negocio en este controlador, lo que permite a este controlador delegar la lógica de negocio relacionada con las operaciones de asistencias a estos servicios, mejorando la organización del código al separar las responsabilidades entre el controlador y los servicios, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios

const getErrorMessage = (error: unknown, defaultMessage: string) => {// Función para obtener el mensaje de error a partir de un error desconocido, lo que permite a este controlador manejar los errores de manera estructurada y consistente al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, mejorando la gestión de errores al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de estas operaciones
  if (error instanceof Error) return error.message;// Si el error es una instancia de Error, devuelve su mensaje, lo que permite a esta función proporcionar información clara sobre el error que ocurrió durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, mejorando la gestión de errores al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de estas operaciones
  return defaultMessage;// Si el error no es una instancia de Error, devuelve un mensaje predeterminado, lo que permite a esta función proporcionar información clara sobre el error que ocurrió durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, incluso en casos donde el error no sea una instancia de Error, mejorando la gestión de errores al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de estas operaciones
};

const getStatusCode = (error: unknown, defaultStatus: number) => {// Función para obtener el código de estado HTTP a partir de un error desconocido, lo que permite a este controlador manejar los errores de manera estructurada y consistente al proporcionar códigos de estado HTTP adecuados según el tipo de error que ocurra durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, mejorando la gestión de errores al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de estas operaciones
  if (Boom.isBoom(error)) {// Si el error es un error de Boom, devuelve su código de estado, lo que permite a esta función proporcionar códigos de estado HTTP adecuados según el tipo de error que ocurrió durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, mejorando la gestión de errores al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de estas operaciones
    return error.output.statusCode;// Devuelve el código de estado HTTP del error de Boom, lo que permite a esta función proporcionar códigos de estado HTTP adecuados según el tipo de error que ocurrió durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, mejorando la gestión de errores al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de estas operaciones
  }// Si el error no es un error de Boom, devuelve un código de estado predeterminado, lo que permite a esta función proporcionar códigos de estado HTTP adecuados según el tipo de error que ocurrió durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, incluso en casos donde el error no sea un error de Boom, mejorando la gestión de errores al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de estas operaciones
  return defaultStatus;// Devuelve un código de estado HTTP predeterminado, lo que permite a esta función proporcionar códigos de estado HTTP adecuados según el tipo de error que ocurrió durante la ejecución de las operaciones relacionadas con las asistencias en la aplicación, incluso en casos donde el error no sea un error de Boom, mejorando la gestión de errores al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de estas operaciones
};

export class AsistenciasController {// Declaración de la clase AsistenciasController para manejar las operaciones relacionadas con las asistencias en la aplicación, lo que permite a esta clase organizar y estructurar el código relacionado con las rutas de asistencias en la aplicación, mejorando la organización del código al separar las responsabilidades entre los controladores y los servicios, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios y manejar las respuestas HTTP en los controladores

  static async scan(req: AuthRequest, res: Response) {// Método estático para manejar el escaneo de códigos QR para registrar asistencias, lo que permite a este método ser llamado sin necesidad de instanciar la clase AsistenciasController, facilitando su uso en las rutas de Express para manejar las solicitudes POST relacionadas con el escaneo de códigos QR para registrar asistencias en la aplicación
    try {// Manejo de la lógica para registrar una asistencia a través del escaneo de un código QR, lo que permite a este método procesar la solicitud de escaneo de código QR, delegar la lógica de negocio relacionada con el registro de la asistencia al servicio scanQRService, y responder al cliente con la información de la asistencia registrada o un mensaje de error en caso de que ocurra un error durante el proceso, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado del escaneo de código QR para registrar asistencias
      const result = await scanQRService(req.body, req.user!.id);// Llamada al servicio scanQRService para registrar una asistencia a través del escaneo de un código QR utilizando los datos del cuerpo de la solicitud y el ID del usuario autenticado, lo que permite a este método delegar la lógica de negocio relacionada con el registro de la asistencia a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
      res.status(201).json(result);// Respuesta con el código de estado 201 (Created) y la información de la asistencia registrada en formato JSON, lo que indica al cliente que la solicitud se ha procesado exitosamente y proporciona la información de la asistencia registrada en la respuesta para que el cliente pueda utilizarla según sea necesario
    } catch (error) {// Manejo de errores en caso de que ocurra un error durante el proceso de escaneo de código QR para registrar una asistencia, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación
      res
        .status(getStatusCode(error, 400))// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 400 (Bad Request), lo que permite a este método responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación
        .json({ error: getErrorMessage(error, "Error al registrar asistencia") });// Respuesta con un objeto JSON que contiene el mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de esta operación
    }
  }

  static async balance(req: AuthRequest, res: Response) {// Método estático para manejar la obtención del balance de asistencias de un usuario, lo que permite a este método ser llamado sin necesidad de instanciar la clase AsistenciasController, facilitando su uso en las rutas de Express para manejar las solicitudes GET relacionadas con la obtención del balance de asistencias en la aplicación
    try {// Manejo de la lógica para obtener el balance de asistencias de un usuario, lo que permite a este método procesar la solicitud de obtención del balance de asistencias, delegar la lógica de negocio relacionada con la obtención del balance al servicio getBalanceService, y responder al cliente con la información del balance de asistencias o un mensaje de error en caso de que ocurra un error durante el proceso, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado de la obtención del balance de asistencias
      const total = await getBalanceService(req.user!.id);// Llamada al servicio getBalanceService para obtener el balance de asistencias de un usuario utilizando el ID del usuario autenticado, lo que permite a este método delegar la lógica de negocio relacionada con la obtención del balance de asistencias a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
      res.status(200).json({ total });// Respuesta con el código de estado 200 (OK) y la información del balance de asistencias en formato JSON, lo que indica al cliente que la solicitud se ha procesado exitosamente y proporciona la información del balance de asistencias en la respuesta para que el cliente pueda utilizarla según sea necesario
    } catch (error) {// Manejo de errores en caso de que ocurra un error durante el proceso de obtención del balance de asistencias, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación
      res
        .status(getStatusCode(error, 400))// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 400 (Bad Request), lo que permite a este método responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación
        .json({ error: getErrorMessage(error, "Error al obtener balance") });// Respuesta con un objeto JSON que contiene el mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de esta operación
    }
  }

  static async historial(req: AuthRequest, res: Response) {// Método estático para manejar la obtención del historial de asistencias de un usuario, lo que permite a este método ser llamado sin necesidad de instanciar la clase AsistenciasController, facilitando su uso en las rutas de Express para manejar las solicitudes GET relacionadas con la obtención del historial de asistencias en la aplicación
    try {// Manejo de la lógica para obtener el historial de asistencias de un usuario, lo que permite a este método procesar la solicitud de obtención del historial de asistencias, delegar la lógica de negocio relacionada con la obtención del historial al servicio getHistorialService, y responder al cliente con la información del historial de asistencias o un mensaje de error en caso de que ocurra un error durante el proceso, mejorando la gestión de solicitudes y respuestas en la aplicación al proporcionar información clara sobre el resultado de la obtención del historial de asistencias
      const asistencias = await getHistorialService(req.user!.id);
      res.status(200).json(asistencias);// Respuesta con el código de estado 200 (OK) y la información del historial de asistencias en formato JSON, lo que indica al cliente que la solicitud se ha procesado exitosamente y proporciona la información del historial de asistencias en la respuesta para que el cliente pueda utilizarla según sea necesario
    } catch (error) {
      res
        .status(getStatusCode(error, 400))// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 400 (Bad Request), lo que permite a este método responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de esta operación
        .json({ error: getErrorMessage(error, "Error al obtener historial") });// Respuesta con un objeto JSON que contiene el mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la ejecución de esta operación, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de esta operación
    }
  }
}
