import { Router } from "express";// Importación de la función Router del módulo "express" para crear un enrutador de Express, lo que permite a este módulo definir rutas específicas para manejar las solicitudes relacionadas con las asistencias en la aplicación, mejorando la organización del código al separar las rutas relacionadas con las asistencias en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con las asistencias en este enrutador
import { authMiddleware } from "../../middlewares/authMiddleware";// Importación del middleware de autenticación para proteger las rutas relacionadas con las asistencias, lo que permite a este módulo asegurar que solo los usuarios autenticados puedan acceder a estas rutas y realizar operaciones relacionadas con las asistencias, mejorando la seguridad de la aplicación al controlar el acceso a estas rutas según el estado de autenticación del usuario
import { roleMiddleware } from "../../middlewares/roleMiddleware";// Importación del middleware de roles para proteger las rutas relacionadas con las asistencias, lo que permite a este módulo asegurar que solo los usuarios con los roles adecuados puedan acceder a estas rutas y realizar operaciones relacionadas con las asistencias, mejorando la seguridad de la aplicación al controlar el acceso a estas rutas según los roles de los usuarios autenticados
import { AsistenciasController } from "./asistencias.controller";// Importación del controlador de asistencias para manejar las solicitudes relacionadas con las asistencias, lo que permite a este módulo delegar la lógica de negocio relacionada con las asistencias a este controlador, mejorando la organización del código al separar las responsabilidades entre el enrutador y el controlador, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con las asistencias en este controlador

export const router = Router();// Creación de un nuevo enrutador de Express para manejar las rutas relacionadas con las asistencias, lo que permite a este módulo definir rutas específicas para manejar las solicitudes relacionadas con las asistencias en la aplicación, mejorando la organización del código al separar las rutas relacionadas con las asistencias en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con las asistencias en este enrutador

router.post("/scan", authMiddleware, roleMiddleware(["familia"]), AsistenciasController.scan);// Ruta para manejar el escaneo de una actividad para registrar la asistencia, protegida por el middleware de autenticación y el middleware de roles para asegurar que solo los usuarios autenticados con el rol de "familia" puedan acceder a esta ruta y realizar la operación de escaneo para registrar la asistencia, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación y los roles de los usuarios
router.get("/balance", authMiddleware, roleMiddleware(["familia"]), AsistenciasController.balance);// Ruta para manejar la obtención del balance de asistencias de un usuario, protegida por el middleware de autenticación y el middleware de roles para asegurar que solo los usuarios autenticados con el rol de "familia" puedan acceder a esta ruta y realizar la operación de obtención del balance de asistencias, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación y los roles de los usuarios
router.get("/historial", authMiddleware, roleMiddleware(["familia"]), AsistenciasController.historial);// Ruta para manejar la obtención del historial de asistencias de un usuario, protegida por el middleware de autenticación y el middleware de roles para asegurar que solo los usuarios autenticados con el rol de "familia" puedan acceder a esta ruta y realizar la operación de obtención del historial de asistencias, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación y los roles de los usuarios

export default router;// Exportación del enrutador de asistencias para que pueda ser utilizado en otras partes de la aplicación, lo que permite a este módulo ser importado y utilizado en el archivo principal de la aplicación para integrar las rutas relacionadas con las asistencias en la aplicación, mejorando la modularidad y la organización del código al centralizar las rutas relacionadas con las asistencias en este módulo específico y facilitar su integración en la aplicación
