import { Router } from "express"; // Importación de la función Router del módulo "express" para crear un enrutador de Express, lo que permite a este módulo definir rutas específicas para manejar las solicitudes relacionadas con las actividades en la aplicación, mejorando la organización del código al separar las rutas relacionadas con las actividades en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con las actividades en este enrutador
import { authMiddleware } from "../../middlewares/authMiddleware";// Importación del middleware de autenticación para proteger las rutas relacionadas con las actividades, lo que permite a este módulo asegurar que solo los usuarios autenticados puedan acceder a estas rutas y realizar operaciones relacionadas con las actividades, mejorando la seguridad de la aplicación al controlar el acceso a estas rutas según el estado de autenticación del usuario
import { roleMiddleware } from "../../middlewares/roleMiddleware";// Importación del middleware de roles para proteger las rutas relacionadas con las actividades, lo que permite a este módulo asegurar que solo los usuarios con los roles adecuados puedan acceder a estas rutas y realizar operaciones relacionadas con las actividades, mejorando la seguridad de la aplicación al controlar el acceso a estas rutas según los roles de los usuarios autenticados
import { ActividadesController } from "./actividades.controller";// Importación del controlador de actividades para manejar las solicitudes relacionadas con las actividades, lo que permite a este módulo delegar la lógica de negocio relacionada con las actividades a este controlador, mejorando la organización del código al separar las responsabilidades entre el enrutador y el controlador, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con las actividades en este controlador

export const router = Router();// Creación de un nuevo enrutador de Express para manejar las rutas relacionadas con las actividades, lo que permite a este módulo definir rutas específicas para manejar las solicitudes relacionadas con las actividades en la aplicación, mejorando la organización del código al separar las rutas relacionadas con las actividades en un módulo específico y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar las rutas relacionadas con las actividades en este enrutador

router.post("/", authMiddleware, roleMiddleware(["gestor"]), ActividadesController.create);// Ruta para manejar la creación de una nueva actividad, protegida por el middleware de autenticación y el middleware de roles para asegurar que solo los usuarios autenticados con el rol de "gestor" puedan acceder a esta ruta y realizar la operación de creación de una nueva actividad, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación y los roles de los usuarios
router.patch("/:id", authMiddleware, roleMiddleware(["gestor"]), ActividadesController.update);// Ruta para manejar la actualización de una actividad existente utilizando el valor del parámetro de ruta "id", protegida por el middleware de autenticación y el middleware de roles para asegurar que solo los usuarios autenticados con el rol de "gestor" puedan acceder a esta ruta y realizar la operación de actualización de una actividad específica, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación y los roles de los usuarios
router.delete("/:id", authMiddleware, roleMiddleware(["gestor"]), ActividadesController.delete);// Ruta para manejar la eliminación de una actividad existente utilizando el valor del parámetro de ruta "id", protegida por el middleware de autenticación y el middleware de roles para asegurar que solo los usuarios autenticados con el rol de "gestor" puedan acceder a esta ruta y realizar la operación de eliminación de una actividad específica, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación y los roles de los usuarios
router.get("/", authMiddleware, ActividadesController.list);// Ruta para manejar la obtención de todas las actividades, protegida por el middleware de autenticación para asegurar que solo los usuarios autenticados puedan acceder a esta ruta y realizar la operación de obtención de todas las actividades, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación del usuario
router.get("/:id", authMiddleware, ActividadesController.getById);// Ruta para manejar la obtención de una actividad específica utilizando el valor del parámetro de ruta "id", protegida por el middleware de autenticación para asegurar que solo los usuarios autenticados puedan acceder a esta ruta y realizar la operación de obtención de una actividad específica, lo que mejora la seguridad de la aplicación al controlar el acceso a esta ruta según el estado de autenticación del usuario

export default router;
