import { Response } from "express"; // Importación del tipo Response del módulo 'express' para tipar los objetos de respuesta en los métodos del controlador, lo que permite a TypeScript proporcionar autocompletado y verificación de tipos al trabajar con objetos de respuesta en estos métodos, mejorando la calidad del código y reduciendo errores al garantizar que se utilicen correctamente las propiedades y métodos disponibles en los objetos de respuesta de Express
import Boom from "@hapi/boom";// Importación del módulo 'Boom' para manejar errores de manera consistente en los métodos del controlador, lo que permite a estos métodos lanzar errores con códigos de estado HTTP y mensajes personalizados de manera sencilla, mejorando la gestión de errores en la aplicación al proporcionar una forma unificada de manejar y responder a los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
import { AuthRequest } from "../../middlewares/authMiddleware";// Importación del tipo AuthRequest desde el middleware de autenticación para tipar los objetos de solicitud en los métodos del controlador, lo que permite a TypeScript proporcionar autocompletado y verificación de tipos al trabajar con objetos de solicitud en estos métodos, mejorando la calidad del código y reduciendo errores al garantizar que se utilicen correctamente las propiedades y métodos disponibles en los objetos de solicitud que incluyen información de autenticación del usuario
import {
  createActividadService,// Importación del servicio createActividadService para crear una nueva actividad, lo que permite a este método del controlador delegar la lógica de negocio relacionada con la creación de actividades a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
  deleteActividadService,// Importación del servicio deleteActividadService para eliminar una actividad, lo que permite a este método del controlador delegar la lógica de negocio relacionada con la eliminación de actividades a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
  getActividadByIdService,// Importación del servicio getActividadByIdService para obtener una actividad por su ID, lo que permite a este método del controlador delegar la lógica de negocio relacionada con la obtención de actividades a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
  listActividadesService,// Importación del servicio listActividadesService para listar las actividades, lo que permite a este método del controlador delegar la lógica de negocio relacionada con la obtención de la lista de actividades a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
  updateActividadService,// Importación del servicio updateActividadService para actualizar una actividad, lo que permite a este método del controlador delegar la lógica de negocio relacionada con la actualización de actividades a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
} from "./actividades.service";// Importación de los servicios relacionados con las actividades para ser utilizados en los métodos del controlador, lo que permite a estos métodos delegar la lógica de negocio relacionada con las operaciones CRUD de actividades a estos servicios, mejorando la organización del código al separar las responsabilidades entre el controlador y los servicios, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
console.log("CREATE CONTROLLER HIT");// Agregado de un log para indicar que se ha accedido al controlador de actividades, lo que puede ser útil para depuración y monitoreo al proporcionar información en los registros sobre cuándo se accede a este controlador y se ejecutan sus métodos, ayudando a identificar patrones de uso y posibles problemas en la aplicación relacionados con las actividades
const getErrorMessage = (error: unknown, defaultMessage: string) => {// Función para obtener el mensaje de error a partir de un error desconocido, lo que permite a los métodos del controlador manejar errores de manera consistente al extraer el mensaje de error de diferentes tipos de errores (como errores de Boom o errores estándar) y proporcionar un mensaje predeterminado en caso de que no se pueda obtener un mensaje específico del error, mejorando la gestión de errores en la aplicación al proporcionar una forma unificada de obtener mensajes de error para responder a los clientes con información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
  if (error instanceof Error) return error.message;// Si el error es una instancia de Error, devuelve su mensaje, lo que permite a los métodos del controlador manejar errores estándar de JavaScript y proporcionar información específica sobre el error que ocurrió durante la ejecución de las operaciones relacionadas con las actividades
  return defaultMessage;// Si el error no es una instancia de Error, devuelve un mensaje predeterminado, lo que permite a los métodos del controlador manejar errores de tipos desconocidos o personalizados y proporcionar información genérica sobre el error que ocurrió durante la ejecución de las operaciones relacionadas con las actividades, mejorando la gestión de errores en la aplicación al garantizar que siempre se proporcione un mensaje de error al cliente, incluso si el error no es un error estándar de JavaScript
};

const getStatusCode = (error: unknown, defaultStatus: number) => {// Función para obtener el código de estado HTTP a partir de un error desconocido, lo que permite a los métodos del controlador manejar errores de manera consistente al extraer el código de estado de diferentes tipos de errores (como errores de Boom) y proporcionar un código de estado predeterminado en caso de que no se pueda obtener un código específico del error, mejorando la gestión de errores en la aplicación al proporcionar una forma unificada de obtener códigos de estado para responder a los clientes con información clara sobre el tipo de error que ocurrió durante la ejecución de las operaciones relacionadas con las actividades
  if (Boom.isBoom(error)) {// Si el error es un error de Boom, devuelve su código de estado, lo que permite a los métodos del controlador manejar errores de Boom y proporcionar códigos de estado específicos que correspondan al tipo de error que ocurrió durante la ejecución de las operaciones relacionadas con las actividades, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre el tipo de error a través del código de estado HTTP
    return error.output.statusCode;// Devuelve el código de estado del error de Boom, lo que permite a los métodos del controlador manejar errores de Boom y proporcionar códigos de estado específicos que correspondan al tipo de error que ocurrió durante la ejecución de las operaciones relacionadas con las actividades, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre el tipo de error a través del código de estado HTTP
  }// Si el error no es un error de Boom, devuelve un código de estado predeterminado, lo que permite a los métodos del controlador manejar errores de tipos desconocidos o personalizados y proporcionar un código de estado genérico para responder a los clientes con información sobre el error que ocurrió durante la ejecución de las operaciones relacionadas con las actividades, mejorando la gestión de errores en la aplicación al garantizar que siempre se proporcione un código de estado HTTP al cliente, incluso si el error no es un error de Boom
  return defaultStatus;// Devuelve el código de estado predeterminado, lo que permite a los métodos del controlador manejar errores de tipos desconocidos o personalizados y proporcionar un código de estado genérico para responder a los clientes con información sobre el error que ocurrió durante la ejecución de las operaciones relacionadas con las actividades, mejorando la gestión de errores en la aplicación al garantizar que siempre se proporcione un código de estado HTTP al cliente, incluso si el error no es un error de Boom
};

export class ActividadesController {// Definición de la clase ActividadesController que contiene los métodos para manejar las operaciones relacionadas con las actividades, lo que permite organizar el código del controlador de manera estructurada y proporcionar una interfaz clara para manejar las solicitudes HTTP relacionadas con las actividades en la aplicación

  static async create(req: AuthRequest, res: Response) {// Método estático para manejar la creación de una nueva actividad, lo que permite a este método ser llamado sin necesidad de instanciar la clase ActividadesController, facilitando su uso en las rutas de Express para manejar las solicitudes POST relacionadas con la creación de actividades en la aplicación
    try {
      const actividad = await createActividadService(req.body, req.user!.id);// Llamada al servicio createActividadService para crear una nueva actividad utilizando los datos del cuerpo de la solicitud y el ID del usuario autenticado, lo que permite a este método delegar la lógica de negocio relacionada con la creación de actividades a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
      res.status(201).json(actividad);// Respuesta con el código de estado 201 (Created) y la actividad creada en formato JSON, lo que indica al cliente que la actividad se ha creado exitosamente y proporciona la información de la actividad creada en la respuesta para que el cliente pueda utilizarla según sea necesario
    } catch (error) {// Manejo de errores en caso de que ocurra un error durante la creación de la actividad, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
      res//
        .status(getStatusCode(error, 400))// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 400 (Bad Request), lo que permite a este método responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió durante la creación de la actividad, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
        .json({ error: getErrorMessage(error, "Error al crear actividad") });// Respuesta con un objeto JSON que contiene el mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la creación de la actividad, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
    }// Manejo de errores en caso de que ocurra un error durante la creación de la actividad, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
  }

  static async list(req: AuthRequest, res: Response) {// Método estático para manejar la obtención de la lista de actividades, lo que permite a este método ser llamado sin necesidad de instanciar la clase ActividadesController, facilitando su uso en las rutas de Express para manejar las solicitudes GET relacionadas con la obtención de la lista de actividades en la aplicación
    try {// Lógica para determinar si se deben listar solo las actividades activas o todas las actividades según el valor del query parameter "activas", lo que permite a este método proporcionar flexibilidad en la obtención de la lista de actividades al permitir a los clientes especificar si desean obtener solo las actividades activas o todas las actividades, mejorando la funcionalidad de la aplicación al adaptarse a diferentes necesidades de los clientes al obtener la lista de actividades
      const soloActivas = req.query.activas === "true";// Determinación de si se deben listar solo las actividades activas o todas las actividades según el valor del query parameter "activas", lo que permite a este método proporcionar flexibilidad en la obtención de la lista de actividades al permitir a los clientes especificar si desean obtener solo las actividades activas o todas las actividades, mejorando la funcionalidad de la aplicación al adaptarse a diferentes necesidades de los clientes al obtener la lista de actividades
      const actividades = await listActividadesService(soloActivas);// Llamada al servicio listActividadesService para obtener la lista de actividades, pasando el valor de soloActivas para determinar si se deben listar solo las actividades activas o todas las actividades, lo que permite a este método delegar la lógica de negocio relacionada con la obtención de la lista de actividades a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
      res.status(200).json(actividades);// Respuesta con el código de estado 200 (OK) y la lista de actividades en formato JSON, lo que indica al cliente que la solicitud se ha procesado exitosamente y proporciona la información de las actividades obtenidas en la respuesta para que el cliente pueda utilizarla según sea necesario
    } catch (error) {// Manejo de errores en caso de que ocurra un error durante la obtención de la lista de actividades, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
      res
        .status(getStatusCode(error, 400))// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 400 (Bad Request), lo que permite a este método responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió durante la obtención de la lista de actividades, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
        .json({ error: getErrorMessage(error, "Error al listar actividades") });// Respuesta con un objeto JSON que contiene el mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la obtención de la lista de actividades, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
    }// Manejo de errores en caso de que ocurra un error durante la obtención de la lista de actividades, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
  }

  static async getById(req: AuthRequest, res: Response) {// Método estático para manejar la obtención de una actividad por su ID, lo que permite a este método ser llamado sin necesidad de instanciar la clase ActividadesController, facilitando su uso en las rutas de Express para manejar las solicitudes GET relacionadas con la obtención de una actividad específica por su ID en la aplicación
    try {// Llamada al servicio getActividadByIdService para obtener una actividad por su ID utilizando el valor del parámetro de ruta "id", lo que permite a este método delegar la lógica de negocio relacionada con la obtención de una actividad específica a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
      const actividad = await getActividadByIdService(req.params["id"] as string);// Llamada al servicio getActividadByIdService para obtener una actividad por su ID utilizando el valor del parámetro de ruta "id", lo que permite a este método delegar la lógica de negocio relacionada con la obtención de una actividad específica a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
      res.status(200).json(actividad);// Respuesta con el código de estado 200 (OK) y la actividad obtenida en formato JSON, lo que indica al cliente que la solicitud se ha procesado exitosamente y proporciona la información de la actividad obtenida en la respuesta para que el cliente pueda utilizarla según sea necesario
    } catch (error) {// Manejo de errores en caso de que ocurra un error durante la obtención de la actividad por su ID, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
      res
        .status(getStatusCode(error, 404))// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 404 (Not Found), lo que permite a este método responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió durante la obtención de la actividad por su ID, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
      
        .json({ error: getErrorMessage(error, "Actividad no encontrada") });// Respuesta con un objeto JSON que contiene el mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la obtención de la actividad por su ID, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades 
    }
  }

  static async update(req: AuthRequest, res: Response) {// Método estático para manejar la actualización de una actividad, lo que permite a este método ser llamado sin necesidad de instanciar la clase ActividadesController, facilitando su uso en las rutas de Express para manejar las solicitudes PUT relacionadas con la actualización de una actividad específica en la aplicación
    try {
      const actividad = await updateActividadService(// Llamada al servicio updateActividadService para actualizar una actividad utilizando el valor del parámetro de ruta "id", los datos del cuerpo de la solicitud y el ID del usuario autenticado, lo que permite a este método delegar la lógica de negocio relacionada con la actualización de una actividad específica a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
        req.params["id"] as string,// Llamada al servicio updateActividadService para actualizar una actividad utilizando el valor del parámetro de ruta "id", los datos del cuerpo de la solicitud y el ID del usuario autenticado, lo que permite a este método delegar la lógica de negocio relacionada con la actualización de una actividad específica a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
        req.body,// Llamada al servicio updateActividadService para actualizar una actividad utilizando el valor del parámetro de ruta "id", los datos del cuerpo de la solicitud y el ID del usuario autenticado, lo que permite a este método delegar la lógica de negocio relacionada con la actualización de una actividad específica a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
        req.user!.id// Llamada al servicio updateActividadService para actualizar una actividad utilizando el valor del parámetro de ruta "id", los datos del cuerpo de la solicitud y el ID del usuario autenticado, lo que permite a este método delegar la lógica de negocio relacionada con la actualización de una actividad específica a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
      );
      res.status(200).json(actividad);// Respuesta con el código de estado 200 (OK) y la actividad actualizada en formato JSON, lo que indica al cliente que la solicitud se ha procesado exitosamente y proporciona la información de la actividad actualizada en la respuesta para que el cliente pueda utilizarla según sea necesario
    } catch (error) {// Manejo de errores en caso de que ocurra un error durante la actualización de la actividad, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
      res
        .status(getStatusCode(error, 400))// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 400 (Bad Request), lo que permite a este método responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió durante la actualización de la actividad, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
        .json({ error: getErrorMessage(error, "Error al actualizar actividad") });// Respuesta con un objeto JSON que contiene el mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la actualización de la actividad, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
    }
  }

  static async delete(req: AuthRequest, res: Response) {// Método estático para manejar la eliminación de una actividad, lo que permite a este método ser llamado sin necesidad de instanciar la clase ActividadesController, facilitando su uso en las rutas de Express para manejar las solicitudes DELETE relacionadas con la eliminación de una actividad específica en la aplicación
    try {
      await deleteActividadService(req.params["id"] as string, req.user!.id);// Llamada al servicio deleteActividadService para eliminar una actividad utilizando el valor del parámetro de ruta "id" y el ID del usuario autenticado, lo que permite a este método delegar la lógica de negocio relacionada con la eliminación de una actividad específica a este servicio, mejorando la organización del código al separar las responsabilidades entre el controlador y el servicio, y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio en los servicios
      res.status(204).send();// Respuesta con el código de estado 204 (No Content) sin contenido en la respuesta, lo que indica al cliente que la solicitud se ha procesado exitosamente y que la actividad ha sido eliminada, sin proporcionar información adicional en la respuesta
    } catch (error) {// Manejo de errores en caso de que ocurra un error durante la eliminación de la actividad, lo que permite a este método responder al cliente con un mensaje de error y un código de estado HTTP adecuado según el tipo de error que ocurrió, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
      res
        .status(getStatusCode(error, 400))// Respuesta con el código de estado obtenido a partir del error o un código predeterminado de 400 (Bad Request), lo que permite a este método responder al cliente con un código de estado HTTP adecuado según el tipo de error que ocurrió durante la eliminación de la actividad, mejorando la gestión de errores en la aplicación al proporcionar información clara sobre los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
        .json({ error: getErrorMessage(error, "Error al eliminar actividad") });// Respuesta con un objeto JSON que contiene el mensaje de error obtenido a partir del error o un mensaje predeterminado, lo que permite a este método responder al cliente con información clara sobre el error que ocurrió durante la eliminación de la actividad, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las actividades
    }
  }
}
